= Introduction and goals
:navtitle: Introduction

== Project overview

Beep is a social media platform and instant messaging web application with real-time video and audio capabilites, file sharing, and more.

== Document overview

The target of this document is the definition of the technical architecture of the Beep project by the specification of its technical requirements.

This document is available in PDF format on request.

== Intended audience

This document is intended for the team of contributors to the Beep project, and others involved in the design and implementation of the system, as well as any stakeholder or individual interested in the technical architecture of the project.

== Requirements language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in link:https://www.rfc-editor.org/info/bcp14[BCP 14] (link:https://datatracker.ietf.org/doc/html/rfc2119[RFC 2119], link:https://datatracker.ietf.org/doc/html/rfc8174[RFC 8174]) when, and only when, they appear in all capitals, as shown here.

== Stakeholders

[cols="2,2,3"]
|===
|Name |Role |Contact

|HÉRITIER Léo
|Project overseer & Client
|leo.heritier at umontpellier.fr

|SOULTANEM Frédéric
|Documentation overseer & Client
|frederic.soultanem at gmail.com

|TCHILINGUIRIAN Théo
|Project contributor
|theo.tchilinguirian at etu.umontpellier.fr

|DO Students
|Project contributors
|theo.tchilinguirian at etu.umontpellier.fr

|===
