= Introduction and goals
:navtitle: Introduction

== Document overview

Beep is a social media platform and instant messaging web application with real-time video and audio capabilites, file sharing, and more.

The target of this document is the definition of the technical architecture of the Beep project by the specification of its technical requirements.

This document is available in PDF format on request.

== Requirements language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in link:https://www.rfc-editor.org/info/bcp14[BCP 14] (link:https://datatracker.ietf.org/doc/html/rfc2119[RFC 2119], link:https://datatracker.ietf.org/doc/html/rfc8174[RFC 8174]) when, and only when, they appear in all capitals, as shown here.

== Stakeholders

[cols="2,2,3"]
|===
|Name |Role |Contact

|HÉRITIER Léo
|Project overseer & Client
|leo.heritier@umontpellier.fr

|SOULTANEM Frédéric
|Documentation overseer & Client
|frederic.soultanem@gmail.com

|TCHILINGUIRIAN Théo
|Project contributor
|theo.tchilinguirian@etu.umontpellier.fr

|DO Students
|Project contributors
|

|===
