= Software infrastructure

This chapter defines the software infrastructure layout of the system. This includes orchestration systems and networks. xref:glossary.adoc#definitions-of-terms[_Business services_] are deployed on top of this software infrastructure.

== Deployment layout

UML deployment diagram
https://www.uml-diagrams.org/deployment-diagrams-overview.html

UML Component diagram? Or some other diagram to show the software infrastructure components and their relationships, the software infrastructure architecture.

- Proxmox Virtual Environment (PVE) cluster MAY

- Kubernetes (K8s) cluster MUST
- Ceph cluster

Smartmontools on top of PVE to monitor the disks and predict disk failure on top of ceph, send alerts... SHOULD

K8s on proxmox

Kube on proxmox

== Network layout

DMZ, Zoning réseau -> découpage logique et physique …
- Matrices de flux réseau

Linkerd svc mesh

svc discovery (server side) with kube's dns. Linkerd handles load balancing over kube's dns. Each business svc just sends request to sidecar proxy, via sidecar. Sidecar also improves observability (tracing haeders, etc), same for mTLS security. Software infra logic is bigger/more complex softinfra, but business service logic is simplexer. Same for fault tolerance logic.
Also more control over external and internal connections/incoming/outgoing requests. Managed by a control plane that pushes config, handles svc discovery, certificates...
From developer's perspective: only preocuppied about their core business logic. I send a request to localhost, and the mesh handles the rest. Still doing gRPC, but not worry about how everything about security, failover etc... Is done/implemented/configured around it.

Linkerd or istio? What about the future?

What the svc mesh does:
between two services grpc call:
- routing and discovery
- encryption
- metrics
- logs
- authorization and authentication
- timeout
- retry
- circuit breaker
- fault tolerance
- and more (lb? rate limiting?...)

Provides
Routing, resilience, security, observability.

=== Network security

Linkerd MUST be configured to provide and enforce mTLS between business services automatically.

Network policies, namespaced apps

mTLS between services (both have client - server certs. Managed by svc mesh linkerd) MUST

TLS for the outside world. HTTPS api gateway service. PKI certificates. kube? Linekrd? MUST

=== Fault tolerance

Network fault tolerance is provided by linkerd's implementation of circuit breakers, retries and timeouts.
-> What MUST be configured/setup, how? Technical architecture requirements.

=== Observability

Linkerd-vis to connect to prometheus and grafana (additional services) to store historical metrics.

== Security

=== Operating systems

Every operating system running in the system MUST be either:

- The latest actively maintained LTS GNU/Linux version, including derivative distributions,
- The latest actively maintained OpenBSD version, including derivate distributions.

=== Dependencies

Graphical components such as windowing systems, desktop environments, and graphical applications SHOULD NOT be installed on the system.

=== Data confidentiality

All sensitive information MUST be encrypted using any secure encryption algorithm.
//TODO: préciser les contraintes sur ces algos (institut qui les vérifie, assure leur non-breach state, etc) Aussi peut être en proposer, en mode "such as AES" etc?

Sensitive informations includes:

- xref:glossary.adoc#definitions-of-terms[_Core user identity_] information.
- xref:glossary.adoc#definitions-of-terms[_Beep-specific user identity_] information.

=== Data integrity

Hard drives SHOULD be configured in a software RAID1 array.

Disk backups MUST be setup to run bi-weekly.

=== Data availability

=== Automatic continuity plan setup config tech archi

Detection, handling of attacks/pbs. Auto IP banning, throttling, etc...
