# beep-tad

Beep Technical Architecture Document and transition to a microservices architecture.

## Building the TAD

### Prerequisites

To locally build the TAD, you need to have the following tools installed:

- asciidoctor
- asciidoctor-pdf
- rouge
- antora node packages: antora/cli, antora/site-generator-default
- pnpm

To build the AsciiDoc document to a PDF, execute the following command:

```bash
asciidoctor-pdf -o beep-tad.pdf beep.adoc
```

= Demo Documentation Component B
// URLs
:url-project: https://antora.org
:url-docs: https://docs.antora.org
:url-org: https://gitlab.com/antora
:url-group: {url-org}/demo
:url-demo-site: https://antora.gitlab.io/demo/docs-site
:url-site-readme: {url-group}/docs-site/blob/master/README.adoc
:url-opendevise: https://opendevise.com

Component B is an example of a documentation component.
It is used by the {url-demo-site}[Antora Demo site].
The playbook and instructions for the Demo site are located in the {url-site-readme}[Demo site playbook project].

== Resources

* {url-project}[Antora Project Site]
* {url-docs}[Antora Docs]
* {url-org}[Antora Repositories]

== Copyright and License

Copyright (C) 2017-present by OpenDevise Inc. and the individual contributors to Antora.

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.
