= Authentication service
:navtitle: Authentication

Authorization and identification steps

Keycloak
POC

authenticate users and external requests (such as coming from bot accounts, webhooks, APIs/SDKs, etc.)
not authenticate internal requests, right? Cuz mTLS in svc mesh?...?




= Service X

This chapter defines the technical architecture requirements specific to the X service. These requirements MUST be met by the X service implementation.

== Behavior

The X service is a xref:glossary.adoc#definitions-of-terms[_business service_]. The X service MUST provide the user stories specified in the following table through the implementation of its interfaces.

[cols="1,2,2"]
|===
|As a |I want to |So that I can

|Guest
|Create an account
|Use the features of Beep.

|===

== Communication

=== Protocol

Every interface implemented by the X service MUST only use the gRPC protocol.

=== Data format

All data transferred via the interfaces MUST be transferred in Protocol Buffers format.

=== Data Transfer Objects

The below Data Transfer Objects (DTO) define the data structures transferred from and to the X service via its interfaces. They are defined as "messages" according to the link:https://protobuf.dev/programming-guides/proto3/[_proto3 revision of the Protocol Buffers language_] format.
//TODO: this link is external, so not persistent. Possibly replace with local copy or reference in appendix.

//TODO: support proto language (with Rouge?)
[source,js]
----
/**
 * SearchRequest represents a search query, with pagination options to
 * indicate which results to include in the response.
 */
message SearchRequest {
  string query = 1;

  // Which page number do we want?
  int32 page_number = 2;

  // Number of results to return per page.
  int32 results_per_page = 3;
}
----

=== API calls

The below API calls define the functions name Remote Procedure Calls (RPC) that the X service provides implement. The X service MUST implement the API calls defined in the following table.
The X service MUST provide the API calls defined below define the data structures transferred from and to the X service via its interfaces. They are defined as "RPCs" (Remote Procedure Calls) according to the link:https://protobuf.dev/programming-guides/proto3/[_proto3 revision of the Protocol Buffers language_] format.
//TODO: this link is external, so not persistent. Possibly replace with local copy or reference in appendix.

=== Interfaces

The below table defines the interfaces of the X service. +
Each interface is defined by its source service, destination service, API call, input data structure and output data structure.

The X service MUST implement the interfaces defined in the following table.

[cols="1,1,1,1,1"]
|===
|From |To |API call |Input DTO |Output DTO

|API Gateway
|Service X
|ServiceXRPC
|SearchRequest
|ServiceXResponse

|===

== State management

=== Databases

The X service MUST only use the link:https://www.postgresql.org/[PostgreSQL] database management system to store all persistent data.
//TODO: this link is external, so not persistent. Possibly replace with local copy or reference in appendix.

This database is a dependency of the X service.

Class diagram of the database schema

== Deployment

The X service and its dependencies MUST be deployed in a "X" namespace inside a Kubernetes cluster.

== Programming language

The X service MUST be implemented in the Rust programming language.
