= General requirements

This chapter defines the technical architecture requirements specific to every xref:glossary.adoc#definitions-of-terms[_business service_]. These requirements MUST be met by every business service implementation.

== Dependencies

This chapter defines _business services_ dependencies constraints and requirements.

=== Languages

Authorized Languages (compiled, not interpreted, not resource hungry java, not memory unsafe C), frameworks, package dependency

=== Libraries

Frameworks, packages, libraries

==== Library deprecation

must be lts, supported, must conduct monthly audit on deprecated libraries in every services. (WAIT THATS NOT TECHNICAL ARCHI, is it? I can specify that every used libraries MUST do X or be X, but how can I specify a technical architecture requirement of doing audits... automatically maybe? Like a cron and alters? idk...)

=== Databases

Authorized databases/db technologies

==== Scaling databases

== Inter-service communication

Pattern that they communicate together directly. OR via the api gateway???
communication interfaces architecture schema

Pattern: server-side service discovery with linkerd svc mesh doing the hard work of load balancing services. Kubernetes, when a pod starts, it's automatically registered, as part of the internal DNS system.

=== Communication protocol

protobuff or avro or http json or...

=== HTTPS/mTLS/Secure certificates handling n stuf

=== Network policies, grpc service mesh linkerd

== Fault tolerance

== Observability

=== System health

Each service MUST implement the 3 k8s default probes

=== Logging

Every service MUST implement a health endpoint

==== Logging endpoint

==== Logging interface

stdout

==== Logs format

Logs MUST follow the below format:

```

```
