= Service segmentation

This chapter defines the technical architecture requirements of xref:glossary.adoc#definitions-of-terms[_business services_] of Beep. Each business service MUST implement those requirements.

Technical architecture requirements specific to each business service are defined in their respective chapters.

== Service landscape layout

The following table defines the segmentation of Beep's xref:glossary.adoc#definitions-of-terms[_usage scenarios_] into business services.

[cols="1,2"]
|===
|Service name |Goal and provided features

|Authentication
|Authenticate users and other external requests, manage xref:glossary.adoc#definitions-of-terms[_core user identity_].

|Authorization
|Manage user and resources permission relationships, user roles.

|Call
|Enable users to share voice/video feeds with minimal latency in voice channels.

|Chat
|Manage text channels and messages lifecycle.

|Files
|Manage file storage and retrieval.

|Frontend
|Provide a web interface to users to arrange the lifecycle of usage scenarios on the web application.

|Notification
|Manage push notifications sent to devices.

|Search
|Provide results to search queries for servers, channels, users, messages and files.

|Server
|Manage servers and members lifecycle.

|Status
|Manage user ephemeral status information (online, typing). (websocket connections and the like..)

|User
|Manage xref:glossary.adoc#definitions-of-terms[_Beep-specific user identity_].

|===

The following UML "Component" diagram describes the layout of the business services of Beep.

.UML "Component" diagram of Beep.
image::appendices/beep-uml-use-case-diagram-light.svg[Fig. 2. UML "Component" diagram of Beep.,link=https://beep.theotchlx.me/beep-tad/1/_images/business/beep-uml-component-diagram-light.svg,window=_blank]
//TODO: refaire un second diagramme de composants avec des blocs au lieu des services et dedans deux composants : l'applicatif et la bdd associée. Peut être les sidecars aussi?? nan...?

=== Dependencies

Authorized Languages (compiled, not interpreted, not resource hungry java, not memory unsafe C), frameworks, package dependency