= Service X

This chapter defines the technical architecture requirements specific to the X service. These requirements MUST be met by the X service implementation.
(This is a service template)

== Usage scenarios

The X service is a xref:glossary.adoc#definitions-of-terms[_business service_] that aims to provide the following usage scenarios.

== Communication

=== Protocol

Every interface implemented by the X service MUST use the gRPC protocol.

=== Data format

All data transferred MUST be transferred in protobuf format.

=== Data Transfer Objects

The below Data Transfer Objects (DTO) define the data structures transferred from and to the X service via its interfaces. They are defined using the link:https://protobuf.dev/programming-guides/proto3/[_proto3 revision of the Protocol Buffers language_] format.
//TODO: save the page as of this date? To have it statically in this doc?

[source,js]
----
/**
 * SearchRequest represents a search query, with pagination options to
 * indicate which results to include in the response.
 */
message SearchRequest {
  string query = 1;

  // Which page number do we want?
  int32 page_number = 2;

  // Number of results to return per page.
  int32 results_per_page = 3;
}
----

=== Interfaces

The below table defines the interfaces of the X service. Each interface is defined by its source service (under "From"), destination service (under "To"), API call (under "Route"),input data structure (under "Input DTO") and output data structure (under "Output DTO").
For gRPC, the "Route" column is the name of the RPC method.
//For REST, the "Route" column is the HTTP verb and URL path.

[cols="1,1,1,1,1"]
|===
|From |To |Route |Input DTO |Output DTO

|API Gateway
|Service X
|ServiceXRPC
|ServiceXRequest
|ServiceXResponse

|===

== State management

Database

Internal state specification (none to be stateless, etc - in case of failure, etc)

Behavior (= implemented usage scenarios) and .



