= Business services requirements
:navtitle: General requirements

This chapter defines the technical architecture requirements specific to xref:glossary.adoc#definitions-of-terms[_business services_]. These requirements MUST be met by every business service implementation.

== Deployment

Business services MUST be deployed in a Kubernetes cluster as containers inside pods.

== Communication

=== Layout

Business services MUST only communicate with each other synchronously.

Pattern: server-side service discovery with linkerd svc mesh doing the hard work of load balancing services. Kubernetes, when a pod starts, it's automatically registered, as part of the internal DNS system.

=== Protocols

Interfaces implemented by business services MUST only use any of the following protocols in the application layer of the OSI model:

- gRPC
- WebSocket
//TODO: Also HTTP is only for frontend and gateway, which aren't business services? Is this also the case for WebSocket?

=== Data formats

All data transferred via the interfaces MUST only be transferred in either of the following data formats:

- Avro in binary format.
- Protocol Buffers in binary format.

== State management

=== Databases

Business services MAY have a database dependency. If so, it MUST only use any of the following database management systems:

- PostgreSQL
- MongoDB
- Valkey
- MinIO

This database is a dependency of the X service.

== Programming languages

Business services MUST only be implemented using any of the following programming languages:

- Erlang (including Gleam and Elixir)
- Go
- Rust

== Observability

=== System health

Each service MUST implement the 3 k8s default probes
MUST implement a healthcheck probe

=== Logging

Business services MUST implement a health endpoint

==== Logging endpoint

==== Logging interface

stdout

==== Logs format

Logs MUST follow the below format:

```

```
